excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://fallenshell.github.io
title: "@fallenshell"
tagline: "Thoughts.find(*)"
description: "Hello, this is @fallenshell's blog. Where he talks about things. Code things. And the occasional social critique."
paginate: 5
