excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://fallenshell.github.io
title: "@fallenshell"
tagline: "Thoughts.find(*)"
description: "Hello, this is my blog, where I rant on code, life, and science."
paginate: 5
